project_id = "tcuxcnszolrkozktpilz"

[functions.ai-ticket-assistant]
verify_jwt = true

[functions.billcom-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.create-customer-portal-session]
verify_jwt = true

[functions.create-managed-service-subscription]
verify_jwt = true

[functions.preview-invite-email]
verify_jwt = true

[functions.sync-billcom-invoices]
verify_jwt = true

[functions.sync-billcom-customers]
verify_jwt = true